### ISSUE TITLE
Добавить memo

### ISSUE THREAD

**Issue by EgorRyazanov** [EgorRyazanov/cherry-pies-game#10]
Думаю, добавление ко всем компонентам memo - хорошая практика.  Рекомендую использовать кастомный вид memo - typedMemo. Подробнее: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/37087.

**Comment by Aristockij** [comment]
ох уж этот memo, столько споров из за него. есть мнение, что если можно не применять useMemo то не стоит и ковырять это дело https://habr.com/ru/companies/otus/articles/696610/ 

но хотелось бы узнать мнение Максима на этот вопрос

**Comment by EvgeniyGrokholskiy** [comment]
memo нам не нужно, у  нас нет сложных вычислений и тяжелых для отрисовки компонентов, я против
