### ISSUE TITLE
Единообразие код стайла

### ISSUE THREAD

**Issue by EgorRyazanov** [EgorRyazanov/cherry-pies-game#11]
1) Использовать FC для отображения пропсов в компонентах
2) Привести экспорты компонентов в единый стиль: либо default, либо named. Лично я привык использовать named. На мой взгляд, очень удобен в командной разработке

**Comment by Aristockij** [comment]
1) да
2) зачем использовать named, если подразумевается экспорт 1 функционального компонента?

**Comment by EvgeniyGrokholskiy** [comment]
1. нет: В React сообществе пришли к выводу, что не стоит злоупотреблять  React.FC<Props>, а лучше вообще от него избавляться, т.к. Он заставляет компонент неявно принимать дочерние элементы. Это означает, что компонент будет принимать дочерние элементы, даже если он НЕ должен этого делать. На этот счет написано много литературы. Для изучения пару из них:
[Why I don’t use React.RC] [https://fettblog.eu/typescript-react-why-i-dont-use-react-fc/](url) 
[Why you shouldn’t use React.FC] [https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13](url)
[Avoid React.FC and React.SFC] [https://backstage.io/docs/architecture-decisions/adrs-adr006](url)
[Think twice when using React.FC] [https://spin.atomicobject.com/2022/01/04/think-twice-react-fc/](url)
[Usage of React.RC] [https://spin.atomicobject.com/2022/01/04/think-twice-react-fc/](url)

**Comment by EvgeniyGrokholskiy** [comment]
2. вроде named экспорт позволяет лучше использовать мощности IDE для изменения значений в разных файлах. Например, поменял имя переменной в интерфейсе и во всем коде, где используется эта переменная, изменилось имя. Сам не проверял, всегда использую named

**Comment by EgorRyazanov** [comment]
1 - принял для изучения, спасибо. 
2 - В named для меня есть еще одно преимущество - нельзя переназывать элемент при импорте. Каждый в команде явно понимает, что используется
